""" Idea: a blockchain that can either store healthcare information or store historical information"""

class Node:
    def init(self):
        pass
    def LightNode(self):
        """Stores headers, they can send transactions out. The average user."""
        pass
    def FullNode(self):
        """Full nodes enforce consensus, mine, and validate transactions."""
        pass
class Block:
    def __init__(self):
        pass
    def nonce(self):
        """ This is the number generated by miners
         to make the block has start with x amount of zeros.
         This will in turn lead to the addition of the block to the chain"""
        pass
    def transaction(self):
        """ This is the collection of unconfirmed
         recent transactions that the block stores"""
        pass
    def hash_block(self):
        """This is the unique identifier
        generated by hashing the block header and transaction data"""
        pass
    def merkle_tree(self):
        """Dstruct to store and verify large amounts of transaction data.
        Transactions are hashed and combined in pairs to make a series of hashes.
        The series are combined until a single root hash exists"""
        pass


